### PR TITLE
Actually update resource.

### PR DESCRIPTION
**Pull request by aars**
This extends what I feel was a hack (the `cleanup` method) to fix resources not updating (stuck in dirty state).

### CODE REVIEW

**Comment by pixelhandler** [comment]
@andrewmp1 any chance you can take a look. I'm slammed with stuff to do this next week.

**Comment by andrewmp1** [comment]
Ya, I see the issue as well that when calling updateResource the resource's attributes are still marked as dirty.  Any way you can add a test for this ?

**Comment by aars** [comment]
I'm swamped (aren't we all!). 

Adding a test isn't that easy. The current tests are all very small unit tests that don't really test the whole chain. Just (single) parts of it. It would take me some time to set up a decent test for this. I could, but only in a few weeks or so.

It might be easier to test up a test for this on the `blog-admin` repo, but I couldn't easily reproduce the issue there since I don't have write permissions on the API, so I couldn't get into a 'update-state'.

Also, the actual fix might be a bit more complicated than this hack. Maybe singleton resources?

**Comment by aars** [comment]
Grrr... This is a bit more complicated... the `didUpdateResource` expects the full resources as serialized JSON, it fully replaces all properties (`setProperties`) on the resource. Which would be fitting if the `cacheUpdate` construction worked, and the server _always_ returned a full resource.. which JSONAPI does not force, a `204 no content` would be perfectly valid (and probably break this `didUpdateResource` as well).

I need to do more testing, I will report back. Though if what I expect is true, I'm just going to drop the `didUpdateResource` use... it makes so little sense. For example: Why is the service-cache a mixin, when it is not optional at all?! How do I disable caching? (try setting expireTime on 0 seconds, stuff breaks). And why does `Resource.didUpdateResource` check if the passed `id` matches the id of the resource itself?! The `id` was used in the first place to get the resource to call `didUpdateResource` on, right? What is the use-case where `didUpdateResource` gets called with a payload some other resource? Just seems odd and makes it very hard to understand the codebase.

**Comment by aars** [comment]
I'm closing this PR, will probably send in a new one when I have this all figured out. For one, this line is waaaaay to aggressive: https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/models/resource.js#L536

Simply calling `this.setProperties(json)` on the Resource for example resets all relationship data if the server does not respond in full (including relationships sideloaded and all), and will of course break when the server doesn't return anything at all (in fact, it won't get called since `deserialize` won't do anything, so the resource doesn't get updated at all).

`setProperties` here negates everything that methods like `updateRelationshipsData` should do.

And I also believe that relationships that are pushed (or received) from the server should not constitute a `changedRelationships`, which is they always are now (it doesn't matter "who" adds the relationships).

**Pull request closed without merging**
