### PR TITLE
Fix deserialization of included resources. 

### PR DESCRIPTION
**Pull request by oliverbarnes**
Resource creation expects relationships to be not null, and included resources come without relationships. Added an empty default

Couldn't find a way to replicate this in the tests, though. At least the suite passes with the change, and my app is running smoothly with it, for what it's worth. 

If you'd like to take a look, it'd break on this [this route](https://github.com/oliverbarnes/participate/blob/proposal-list/app/routes/proposals/list.js#L5)

Here's a sample payload it fetches:

```
{
    "data": [
        {
            "attributes": {
                "body": "trest",
                "title": "test"
            },
            "id": "55cb9c464f6c694a69000000",
            "links": {
                "self": "http://localhost:3000/proposals/55cb9c464f6c694a69000000"
            },
            "relationships": {
                "author": {
                    "data": {
                        "id": "55b4e6fe4f6c69b313000000",
                        "type": "authors"
                    },
                    "links": {
                        "related": "http://localhost:3000/proposals/55cb9c464f6c694a69000000/author",
                        "self": "http://localhost:3000/proposals/55cb9c464f6c694a69000000/relationships/author"
                    }
                },
                "suggestions": {
                    "links": {
                        "related": "http://localhost:3000/proposals/55cb9c464f6c694a69000000/suggestions",
                        "self": "http://localhost:3000/proposals/55cb9c464f6c694a69000000/relationships/suggestions"
                    }
                },
                "supports": {
                    "links": {
                        "related": "http://localhost:3000/proposals/55cb9c464f6c694a69000000/supports",
                        "self": "http://localhost:3000/proposals/55cb9c464f6c694a69000000/relationships/supports"
                    }
                }
            },
            "type": "proposals"
        }
    ],
    "included": [
        {
            "attributes": {
                "name": "Oliver Azevedo Barnes"
            },
            "id": "55b4e6fe4f6c69b313000000",
            "links": {
                "self": "http://localhost:3000/authors/55b4e6fe4f6c69b313000000"
            },
            "type": "authors"
        }
    ]
```

### CODE REVIEW

**Comment by pixelhandler** [comment]
I'll take a look tomorrow, thanks.

**Comment by pixelhandler** [comment]
@oliverbarnes the test for the serializer that includes a resource issues this payload https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/fixtures/api/posts/1.json here is the test https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/tests/unit/serializers/application-test.js#L138-L168 

So we'd need to create a test that has no relationships in the included document. So it looks like your example has a proposal that included a related author (but the author doesn't have any relationships). That example relation would need to be simulated in the test.

the test would need:

```
[
        {
            "attributes": {
                "name": "Oliver Azevedo Barnes"
            },
            "id": "55b4e6fe4f6c69b313000000",
            "links": {
                "self": "http://localhost:3000/authors/55b4e6fe4f6c69b313000000"
            },
            "type": "authors"
        }
    ]
```

…as the `mockIncluded ` value that is payload passed into `serializer.deserializeIncluded(mockIncluded, { headers:{} });`

**Comment by pixelhandler** [comment]
@oliverbarnes I pushed up a branch which I think may fix the root of the issue, see: https://github.com/oliverbarnes/ember-jsonapi-resources/compare/fix-relationship-setup-for-included-resource...pixelhandler:fix-relationship-setup-for-included-resource

**Comment by pixelhandler** [comment]
This should be fixed in v0.5.3

**Comment by oliverbarnes** [comment]
awesome, thanks @pixelhandler. I'll test it out and post back if anything comes up

**Pull request closed without merging**
