### PR TITLE
Add assertion for dasherized keys in resource

### LINKED ISSUE #28: "Dasherize" resource attributes
Just recommending that keys given to `Resource#attr` be dasherized by default. This makes serialization same with the `jsonapi-resources` gem, and since the official spec hints at this convention anyway. Thanks!

### PR DESCRIPTION
**Pull request by pixelhandler**
See: http://jsonapi.org/recommendations/#naming  and https://github.com/cerebris/jsonapi-resources#key-format

- `'first-name': attr()` is the JSON API recommendation
- `images: hasMany('image-assets')` and `image: hasOne('image-asset')` are preferred

Failed assertion handled by console.warn

[Closes #28]

### CODE REVIEW

**Comment by pixelhandler** [comment]
@erikap @oliverbarnes @barelyknown @vinnicc  What do you think about using console.warn for any use of attributes (keys in payload) that are not dasherized?

**Comment by vinnicc** [comment]
This helps a lot, but what's your opinion on dasherizing automatically to avoid:

```javascript
'first-name': attr(),
firstName: Ember.computed.alias('first-name'),
```

A common use case is when setting attributes via `set`, we would want to be able to pass in `firstName` I think.

**Comment by oliverbarnes** [comment]
I think it's helpful too. I was bit by mistakes non-dasherizing my payloads (with ED), and a warning would have saved me time debugging

**Comment by madnificent** [comment]
@erikap (on my phone, will fix styling and typos later) My opninion is that we shouldn't place /requirements/ on following the recommendations.  A great addon would make the recommended path easy, and the non-recommended path possible.  In this specific case, that hints towards being allowed to specify the JSON's key used for the computed property in attr, hasMany and hasOne.  We can easily place a default value of the optional argument on the recommended JSON key.  Implementing the feature @vinnicc would want.  IE: storePrice: attr();  would be equivalent to storePrice: attr("store-price").  The same can hold for relationships.  Optional warnings for incomplete objects could be valid still.  However, an earlier reading of the spec dis not seem to require the server to return /all/ keys the object could have whenever the object is returned.  Hence an option object, rather than a string value could be preferable.  ie: our earlier example would become storePrice: attr( { key: 'store-price', requireKey: false } );

**Comment by pixelhandler** [comment]
@madnificent the concept so far has been to warn in the console that the recommendation naming is dasherized but not require dasherized names. So the non recommended path is still possible, the warning in the console is to help make the recommended path easier. The current `attr()` helper doesn't require a type like `attr('string')` but thought that one day that may be needed. I think the formatting of the attributes can be done with the blueprint by passing attribute names to the generator. The Ember CLI default blueprint does that already and is specific to Ember Data. I have not implemented the scaffolding of attributes in the resource yet. But that would be the best place to facilitate default attribute naming conventions, e.g. `ember g resource post attr:updated-by` or `ember g resource post attr:updatedBy`. Or something like that.

**Comment by pixelhandler** [comment]
@vinnicc I think this console warning will help people become aware of the recommendation and still leave the resource conventions up to developers. It's easy to add computed properties if you prefer camelCased attributes.

**Pull request merged**
