### PR TITLE
Add yarn.lock file for users of yarn package manager.

### PR DESCRIPTION
**Pull request by andrewmp1**
[Yarn](https://yarnpkg.com/) is a new package manager alternative to npm and its great.

This PR adds in a yarn.lock file that specifies the dependencies so that it installs exactly the versions expected in this file.  It should be transparent to anyone using the npm client.

(npm install -g yarn)
Usage docs for yarn.lock are here: https://yarnpkg.com/en/docs/yarn-lock

Excerpts on how to use yarn.lock:

#Managed by Yarn

Your yarn.lock file is auto-generated and should be handled entirely by Yarn. As you add/upgrade/remove dependencies with the Yarn CLI, it will automatically update your yarn.lock file. Do not edit this file directly as it is easy to break something.

#Check into source control

All yarn.lock files should be checked into source control (e.g. git or mercurial). This allows Yarn to install the same exact dependency tree across all machines, whether it be your coworker’s laptop or a CI server.

### CODE REVIEW

**Comment by pixelhandler** [comment]
@andrewmp1 can you update the description on this PR for how to use yarn with this addon?

**Comment by andrewmp1** [comment]
@pixelhandler updated PR with a better description.

**Comment by pixelhandler** [comment]
@andrewmp1 also can you add notes here on how to maintain the new yarn.lock file?

**Comment by andrewmp1** [comment]
@pixelhandler Okay, added more information about yarn.lock file.

**Comment by pixelhandler** [comment]
@andrewmp1 I'm curious if CI would need to be setup to use the yarn.lock file. That is does the "All checks passed" still mean according the the npm install of today? Can you look into how to utilize the yarn.lock file with the test runner in CI (Travis). This addon uses ember-try. So I'm curious if Ember-Try will embrace Yarn as well.

**Comment by pixelhandler** [comment]
@andrewmp1 I guess we can try to figure out how to utilize the yarn file in the build in a separate PR.

**Pull request merged**
